// @ts-expect-error generated by the OpenNext Cloudflare build step
import openNextWorker from './.open-next/worker.js'

type WorkerEnv = Record<string, unknown>

function setCloudflareContext(env: WorkerEnv, ctx: ExecutionContext) {
  const cloudflareContextSymbol = Symbol.for('__cloudflare-context__')
  ;(globalThis as Record<PropertyKey, unknown>)[cloudflareContextSymbol] = {
    cf: undefined,
    ctx,
    env,
  }
}

export default {
  async fetch(request: Request, env: WorkerEnv, ctx: ExecutionContext) {
    return openNextWorker.fetch(request, env, ctx)
  },

  async scheduled(_event: ScheduledEvent, env: WorkerEnv, ctx: ExecutionContext) {
    setCloudflareContext(env, ctx)

    try {
      const [{ getPayload }, payloadConfigModule, { cleanupAllOrphanMedia }] = await Promise.all([
        import('payload'),
        import('./src/payload.config'),
        import('./src/media/orphanCleanup'),
      ])

      const payload = await getPayload({ config: await payloadConfigModule.default })
      const result = await cleanupAllOrphanMedia({ payload })

      console.info(
        `[media-cleanup:cron] scanned=${result.scannedCount} referenced=${result.referencedCount} deleted=${result.deletedIds.length}`,
      )
    } catch (error) {
      console.error(
        `[media-cleanup:cron] failed: ${error instanceof Error ? error.message : 'unknown error'}`,
      )
      throw error
    }
  },
}
